swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /:
    get:
      operationId: Say
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
